name: Build App

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Install NPM dependencies
      run: |
        npm install --production --unsafe-perm
      #Check dependency
    - uses: sburris/dependency-check-action@master
      with:
        Project-Name: TestApp
      #Archive dependency check
    - name: Archive dependency check reports
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
      #Buil and push docker
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: vincgiauffret/cd
        tag_with_sha: true
